apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: kedar1704/node-app  # Replace with your image name and tag
        ports:
        - containerPort: 3000
        env:
        - name: ENVIRONMENT
          value: "production"  # Replace with your environment variable if needed
