apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: kedar1704/python-app  # Replace with your image name and tag
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "production"  # Replace with your environment variable if needed
