apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80  # This is the port on which the service will be exposed
      targetPort: 5000  # This is the port on which your app is running in the container
  type: LoadBalancer  # Use NodePort if you don't want an external load balancer
